### ISSUE TITLE
Anamorphic lenses?

### ISSUE THREAD

**Issue by antithing** [dcharatan/flowmap#12]
Does this code support images from anamorphic lenses? 
Would the intrinsic data be calculated correctly?

Also, how many parameters are returned for the distortion matrix?

Thanks!

**Comment by dcharatan** [comment]
FlowMap currently only supports pinhole projection with a uniform (shared across x and y) focal length and a principal point at the image center. It doesn't estimate distortion parameters. However, if you're interested in estimating distortion parameters, you could try to add them as regressed/directly optimized variables. I would be happy to provide more details on how to do so if you're interested!

**Comment by dcharatan** [comment]
As for anamorphic lenses, you could probably modify [this function](https://github.com/dcharatan/flowmap/blob/a6f854fb9376fdaf9c40b2a0cf81a2378424fd84/flowmap/model/intrinsics/common.py#L6-L20) to take the anamorphic projection into account. For example, if the anamorphic projection just squeezes the normal projection by 2x on the X axis, you would have to account for the factor of two on line 17.
