### ISSUE TITLE
When running render_point_cloud. py in the paper directory, there are no relevant models in the paper/assets directory

### ISSUE THREAD

**Issue by lowpair** [dcharatan/flowmap#15]
Great job!
Could you please share the models related to paper/assets/exports_birds_compact.pt and paper/assets/flows_tracks_birds_compact.pt? These two pt files are missing when running render_point_cloud. py under paper directory.
May I ask where the exports_birds_compact.pt and flows_tracks_birds_compact.pt models are generated from?

**Comment by dcharatan** [comment]
I've uploaded `exports_birds_compact.pt` and `flows_tracks_birds_compact.pt` to Google Drive [here](https://drive.google.com/drive/folders/1PqByQSfzyLjfdZZDwn6RXIECso7WB9IY?usp=drive_link). I also uploaded the original Lego bird dataset that we used to generate the figures.

Those two files were generated by saving `exports` and `(flows, tracks)` using `torch.save` from within a debugger in `flowmap/overfit.py`. The figures were generated with an earlier version of the code, so the results might be slightly different if you try to recreate the figure exactly.

Be warned that the figure generation code is very specific to the bird scene and quite messy!
