### ISSUE TITLE
how to generate the novel synthesis view videos?

### ISSUE THREAD

**Issue by minounou** [dcharatan/flowmap#16]
Hi, I run the following command and generated images/ply in outputs/local folder successfully, I just have a question: I saw the novel synthesis view videos from your website cameronosmith.github.io/flowmap:  could you let me know how to continue to generate that kind of novel view videos? Thanks! 

(my command):
CUDA_VISIBLE_DEVICES=0 python -m flowmap.overfit dataset=images dataset.images.root=./datasets/flowmap/co3d_bench/ +experiment=low_memory

**Comment by dcharatan** [comment]
Check out the README for a note we added on generating the novel view synthesis results from the paper. We used this [bundle-adjusting version of 3DGS](https://github.com/cameronosmith/gaussian_barf) to generate the results.

FlowMap outputs camera poses in COLMAP format, meaning that in general, it should be compatible with any novel view synthesis pipeline that accepts COLMAP-style datasets.

**Comment by minounou** [comment]
@dcharatan Thank you!
