### ISSUE TITLE
Why not using GMFlow as the default optical flow estimator

### ISSUE THREAD

**Issue by ruili3** [dcharatan/flowmap#19]
Hi

Thanks for the great work and the decently-written, well-commented codebase!

I noticed you also have GMFlow as an alternative optical flow estimator but the default setting is still RAFT. Since GMFlow is a relatively new method with reported scores higher than RAFT, I wonder why you made this selection :) 

Thanks in advance!

**Comment by dcharatan** [comment]
In practice, we found that RAFT gives more accurate/usable optical flow. GMFlow is much faster to run, though, so we use it for pretraining.
