### ISSUE TITLE
how to draw pose with pointclouds 

### ISSUE THREAD

**Issue by LamHoCN** [dcharatan/flowmap#26]
![image](https://github.com/dcharatan/flowmap/assets/19267253/751ca907-051e-4c66-96d6-ab173d6531f9)
hey, how to vis like above in the paper ?

**Comment by cameronosmith** [comment]
Hey, we just used the open3d pointcloud viewer - here's an extremely sphaghetti-code script which I hope is useful until we clean this up and add it to the repo. Just run the python file with the scene '.pt' file in the same directory and it should work, and use the minus keys to decrease the point size for aesthetics 
python: https://drive.google.com/file/d/1ioGIXuKe3qMZ5rgUfQ7uuxLqlPGHbYos/view?usp=sharing
scene file: https://drive.google.com/file/d/1KEBRL7J4KCufKwpdMnOZ2Bc7ROHf1pJS/view?usp=sharing
