### ISSUE TITLE
Use the command: python3 -m flowmap.overfit dataset=images dataset.images.root=/flowmap/data/2; run your own data

### ISSUE THREAD

**Issue by Tiangj9178** [dcharatan/flowmap#27]
Use the command: python3 -m flowmap.overfit dataset=images dataset.images.root=/flowmap/data/2 When running your own dataset, checkpoints/initialization_finetuned.ckpt cannot be found. This checkpoint requires running the pretrain.py file. To get it? Or do I need to download your initialization .ckpt file?
![image](https://github.com/dcharatan/flowmap/assets/166288582/ae8a98c7-009b-4860-8d6e-45471d12a3a0)
![image](https://github.com/dcharatan/flowmap/assets/166288582/5b077070-5427-49d1-bc92-929d1842acc5)

**Comment by dcharatan** [comment]
As indicated in the README, you have to download `initialization_finetuned.ckpt` from [here](https://drive.google.com/drive/folders/1PqByQSfzyLjfdZZDwn6RXIECso7WB9IY) and place it in a `/checkpoints` folder in the top-level `flowmap` directory before running FlowMap.

You can also use `+experiment=ablation_random_initialization_long` if you don't want to use the checkpoint, but this will take much longer to converge.
