### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by wuqun-tju** [dcharatan/flowmap#30]
I run the overfit.py using 15 frames of co3d_bench, but THE 3D results is wrong. Can you explain it ?

![image](https://github.com/dcharatan/flowmap/assets/58416153/f06c1621-fe4e-4fae-9bd8-81bbe0db35be)

**Comment by dcharatan** [comment]
It's hard to tell what's happening with just the point cloud. Can you provide some more details on the scene, the configuration you ran, etc.?

In general, there are two failure modes for FlowMap:

1. Rarely, FlowMap will fall into a "hollow face minimum" where depths are inverted, kind of like [this](https://en.wikipedia.org/wiki/Hollow-Face_illusion).
2. If RAFT optical flow estimation gives bad results, then the FlowMap results will correspondingly be bad.

If you connect FlowMap to wandb, you can see the predicted (FlowMap) and "ground-truth" (RAFT) optical flows alongside the predicted depth maps. This will hopefully provide some insight into what's happening.
