### ISSUE TITLE
Practice of fine-tuning the initial camera poses and intrinsics in Nerfstudio

### ISSUE THREAD

**Issue by Guangyun-Xu** [dcharatan/flowmap#34]
Thank you for your great work!
I did not find a description of fine-turn camera pose and intrinsics in the Nerfstudio paper.
How can I find out the details of such refinement methods?

![image](https://github.com/dcharatan/flowmap/assets/38279883/a9e54df4-5ff9-4d38-82ef-29539ec35028)

**Comment by dcharatan** [comment]
The most well known paper that does this is [BARF](https://chenhsuanlin.bitbucket.io/bundle-adjusting-NeRF/), and the current state of the art (as far as I know) is [CamP](https://camp-nerf.github.io/).

**Comment by dcharatan** [comment]
Also, see [this section of the README](https://github.com/dcharatan/flowmap/tree/main?tab=readme-ov-file#generating-novel-view-synthesis-results) for a hackily modified version of Gaussian Splatting that does camera refinement.
