### ISSUE TITLE
Dynamic Setting

### ISSUE THREAD

**Issue by skrya** [dcharatan/flowmap#35]
Dear Authors, 

Thanks for the amazing work! I know that this work deals with static setting. I am curious to know if this work can be extended to dynamic setting with optical and foreground and background (static) segmentation available? Please share your thoughts.

Thanks!

**Comment by dcharatan** [comment]
If dynamic parts of the scene were perfectly segmented and FlowMap's losses were masked accordingly, FlowMap would work on dynamic videos (at least for pose estimation). This shouldn't be too hard to implement—you could probably load the static/dynamic mask in the data loader and then multiply it with the pixelwise optical flow loss. The key challenge would probably be ensuring that the segmentation is high enough quality.
