### ISSUE TITLE
About compute_consistency_mask function

### ISSUE THREAD

**Issue by wuqun-tju** [dcharatan/flowmap#37]
Thank you for your excellent work!
In the [code](https://github.com/dcharatan/flowmap/blob/main/flowmap/flow/flow_predictor.py#L79C8-L79C64), I think deltas is used for highlighting accurate flow, but I don't understand the way to get deltas in the code. I think the pixel value on the same position xy of [source] and [target_pixel] are different definitely, they can't be subtracted by position xy.  
lookforward your reply!

**Comment by leo-frank** [comment]
It is just a color consistency check.
