### ISSUE TITLE
Some questions about subsample.py

### ISSUE THREAD

**Issue by Guangyun-Xu** [dcharatan/flowmap#38]
Thanks for you suggestions in #36, I did some experiments with subsample.py and found two problems:

1. [There](https://github.com/dcharatan/flowmap/blob/19ac72b78d010220bd9487553db4fb463ab317d4/flowmap/subsample.py#L78) using 'jpg' format to save image may lose some detail, 'png' format is batter.
2. "last" does not appear to have been updated after [calculating mean_flow](https://github.com/dcharatan/flowmap/blob/19ac72b78d010220bd9487553db4fb463ab317d4/flowmap/subsample.py#L112C1-L131C1).

**Comment by Guangyun-Xu** [comment]
fixed in [commit](https://github.com/dcharatan/flowmap/commit/8bd8d33e6f5cf7a99e4cffbd1dc5a6caa91ad229)

**Comment by dcharatan** [comment]
Thanks for pointing these things out. The second problem in particular is pretty bad. I've pushed a fix -- let me know if it still seems broken.
