### ISSUE TITLE
CUDA OOM error

### ISSUE THREAD

**Issue by phongnhhn92** [dcharatan/flowmap#4]
Hi,

I am trying out the overfitting script on a scene from Mip-NeRF360 but I got OOM cuda error with a 24GB VRAM GPU. I wonder which GPU should I use to run the experiment.

**Comment by zoldaten** [comment]
try to use CPU:
```
device = torch.device("cpu")
...
accelerator="cpu",
```

in overfit.py

**Comment by dcharatan** [comment]
I just pushed a low-memory configuration that works on a 24 GB GPU. You can use it by appending `+experiment=low_memory` to the end of your `python3 -m flowmap.overfit` command. It simply cuts the resolution of the resnet (depth CNN) feature maps by 75%. I tried this on the provided Tanks and Temples Caterpillar scene (150 frames), and it consumes a bit under 12 GB of VRAM.

If you want to run other experiments alongside the low-memory configuration, you can do `+experiment=[low_memory,other_experiment]`.

Note that the initialization was trained at a higher resolution, so it might not work as well with the low-memory configuration. However, on the Caterpillar scene, it seemed to work reasonably well. In my experience, having a high-resolution depth map surprisingly isn't that important for getting accurate poses.

**Comment by leo-frank** [comment]
Everyone who use low_memory as config should notice that simply cut down the resolution will cause the monocular-depth estimation network behave worse.
