### ISSUE TITLE
Generate input data?

### ISSUE THREAD

**Issue by antithing** [dcharatan/flowmap#6]
Hi, and thanks for this code! Would you be able to link to a workflow to generate the flow maps and point tracks to use as input?

Or, does this repo include a full end-to-end pipeline that can simply take an rgb sequence?

**Comment by dcharatan** [comment]
The repo includes the full end-to-end pipeline that takes an RGB sequence as input. There's also a tool that will let you subsample videos for use with FlowMap (see #2 for more details).
