### ISSUE TITLE
Visualize the flowmap results

### ISSUE THREAD

**Issue by avinashay** [dcharatan/flowmap#7]
How can I visualize the results from running the script python3 -m flowmap.overfit dataset=images dataset.images.root=path/to/folder/with/images ?

I see output as a colmap format of cameras.bin, images.bin, points3D.ply

**Comment by dcharatan** [comment]
There are a few options. If you use `wandb.mode=online` and specify settings for Weights and Biases in the main configuration file (`config/overfit.yaml`), visualizations will be logged to the internet. If you want to see the visualizations locally (just images, no graphs), they will be printed to `outputs/local` if `wandb.mode` is `disabled`.
